#!/bin/bash
#SBATCH --job-name=fcdn500tlgn
#SBATCH -N 1
#SBATCH -o ../server_logs/fcdn500tlgn.out 
#SBATCH -e ../server_logs/fcdn500tlgn.err
#SBATCH --mem=128000
#SBATCH --gres=gpu:1
#SBATCH --time=50:00:00
#SBATCH --mail-type=END

echo "Executing on $HOSTNAME"

module load gcc/latest
module load nvidia/latest
module load cudnn/latest

python3 ../notebooks/fcdn-isisc-400-tl-gn.py
